linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        env: CONAN_VERSION=1.10.0
      - <<: *linux
        env: CONAN_VERSION=1.11.0
      - <<: *linux
        env: CONAN_VERSION=1.12.0
      - <<: *linux
        env: CONAN_VERSION=1.13.0
      - <<: *linux
        env: CONAN_VERSION=1.14.0
      - <<: *linux
        env: CONAN_VERSION=1.15.0
      - <<: *linux
        env: CONAN_VERSION=1.16.0
      - <<: *linux
        env: CONAN_VERSION=1.17.0

install:
  - echo "ok"

script:
  - travis_wait 40 ./run.sh $CONAN_VERSION
